// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtQejAXeOeVSrf74QHchVPZfoay2JjC4I',
    appId: '1:842247338489:web:7026290b865acaf23ba528',
    messagingSenderId: '842247338489',
    projectId: 'flutter-test-e3d4c',
    authDomain: 'flutter-test-e3d4c.firebaseapp.com',
    storageBucket: 'flutter-test-e3d4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8eOKu051QlEhR5XeMr4Q1zoWOYjA-zVo',
    appId: '1:842247338489:android:ff8055375f25e4de3ba528',
    messagingSenderId: '842247338489',
    projectId: 'flutter-test-e3d4c',
    storageBucket: 'flutter-test-e3d4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1jh3rvjCI4c_jNH4L8KXgmp4trZAmR9k',
    appId: '1:842247338489:ios:bd1012196918f8103ba528',
    messagingSenderId: '842247338489',
    projectId: 'flutter-test-e3d4c',
    storageBucket: 'flutter-test-e3d4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1jh3rvjCI4c_jNH4L8KXgmp4trZAmR9k',
    appId: '1:842247338489:ios:bd1012196918f8103ba528',
    messagingSenderId: '842247338489',
    projectId: 'flutter-test-e3d4c',
    storageBucket: 'flutter-test-e3d4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtQejAXeOeVSrf74QHchVPZfoay2JjC4I',
    appId: '1:842247338489:web:8999d8423a192a4a3ba528',
    messagingSenderId: '842247338489',
    projectId: 'flutter-test-e3d4c',
    authDomain: 'flutter-test-e3d4c.firebaseapp.com',
    storageBucket: 'flutter-test-e3d4c.firebasestorage.app',
  );

}